blank_issues_enabled: true
contact_links:
  - name: SOLUF-CILPEA Security Policy
    url: https://github.com/SOLUF-CILPEA/SECURITY.md
    about: View security policy
  - name: SOLUF-CILPEA Developers
    url: 
    about: SOLUF-CILPEA homepage
